# Generated by Django 5.2.17 on 2026-08-28 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus Session',
                'verbose_name_plural': 'Focus Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_duration', models.PositiveIntegerField(default=25, verbose_name='Focus Duration (minutes)')),
                ('short_break', models.PositiveIntegerField(default=5, verbose_name='Short Break (minutes)')),
                ('long_break', models.PositiveIntegerField(default=15, verbose_name='Long Break (minutes)')),
                ('sessions_before_long', models.PositiveIntegerField(default=4, verbose_name='Sessions Before Long Break')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro Settings',
                'verbose_name_plural': 'Pomodoro Settings',
            },
        ),
    ]
