# Generated by Django 5.2.17 on 2026-08-28 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('grade_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('test', 'Test'), ('midterm', 'Midterm'), ('exam', 'Exam'), ('project', 'Project'), ('other', 'Other')], default='homework', max_length=20, verbose_name='Grade Type')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Score')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Max Score')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Weight (%)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='semesters.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date'],
            },
        ),
    ]
